image: golang:latest

stages:
  - test

before_script:
  - apt-get update
  - apt-get install --yes  libgl1-mesa-dev xorg-dev
  - mkdir -p ${GOPATH}/src/${GO_PROJECT}
  - cp -r ${CI_PROJECT_DIR}/* ${GOPATH}/src/${GO_PROJECT}/
  - cd ${GOPATH}/src/${GO_PROJECT}
  - go get -t ./...

test:
  stage: test
  script:
    - apt-get install --yes xvfb
    - export DISPLAY=:99
    - Xvfb $DISPLAY -screen 0 1024x768x24 +extension GLX +render -noreset&
    - go test -v -cover ./...