image: golang:latest

stages:
  - test

format:
  stage: test
  before_script:
    - echo "Starting job format in test stage."
  script:
    #- go fmt $(go list ./... | grep -v /vendor/)
    #- go vet $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v /vendor/)
